export const BOGO_VERSION = "0.5.3";

export interface LiveResponse {
	status: "ok" | "error";
	version: string;
	component: string;
	timestamp: string;
	uptime: number;
}

export { generateId } from "./id.js";

export {
	type AddDocPersonInput,
	addDocPersonSchema,
	type BuiltinColumnName,
	builtinColumnNames,
	builtinNameFromKey,
	type ColumnKey,
	type CreateDocTypeInput,
	type CreateDocumentInput,
	type CreateFieldDefInput,
	type CreatePersonInput,
	type CreatePersonTableViewInput,
	type CreateTagInput,
	type CreateWorkspaceInput,
	type CustomFieldDefinition,
	type CustomFieldValue,
	columnKeySchema,
	createDocTypeSchema,
	createDocumentSchema,
	createFieldDefSchema,
	createPersonSchema,
	createPersonTableViewSchema,
	createTagSchema,
	createWorkspaceSchema,
	DEFAULT_TABLE_VIEW_COLUMNS,
	DEFAULT_TABLE_VIEW_NAME,
	type Document,
	type DocumentPerson,
	type DocumentSummary,
	type DocumentType,
	type DocumentVersion,
	type DocumentVersionSummary,
	type EmbeddedTag,
	type FieldType,
	type FilterOperator,
	fieldIdFromColumnKey,
	fieldTypes,
	filterOperators,
	isBuiltinColumnKey,
	isSortableBuiltin,
	isUuidString,
	isValidDateYmd,
	isValidFiniteNumberString,
	type MovePersonInput,
	movePersonSchema,
	type Person,
	type PersonTableView,
	type SetFieldValueInput,
	setFieldValueSchema,
	type Tag,
	type TagScope,
	type TagStats,
	type TagWithCount,
	tagSchema,
	tagStatsSchema,
	tagWithCountSchema,
	UNFILTERABLE_BUILTIN,
	UNSORTABLE_BUILTIN,
	type UpdateDocTypeInput,
	type UpdateDocumentInput,
	type UpdateFieldDefInput,
	type UpdatePersonInput,
	type UpdatePersonTableViewInput,
	type UpdateTagInput,
	type UpdateWorkspaceInput,
	updateDocTypeSchema,
	updateDocumentSchema,
	updateFieldDefSchema,
	updatePersonSchema,
	updatePersonTableViewSchema,
	updateTagSchema,
	updateWorkspaceSchema,
	type ViewFilter,
	type ViewSort,
	validateFilterWireShape,
	viewFilterSchema,
	viewSortSchema,
	type Workspace,
} from "./schemas/index.js";
